---
tags: ,CUDA,bug
title: "Assigning to DeviceNDArray with Ellipsis fails"
html_url: "https://github.com/numba/numba/issues/5170"
user: jakirkham
repo: numba/numba
---

<!--

Thanks for opening an issue! To help the Numba team handle your information
efficiently, please first ensure that there is no other issue present that
already describes the issue you have
(search at https://github.com/numba/numba/issues?&q=is%3Aissue).

For more general "how do I do X?" type questions, please speak to us in real
time on https://gitter.im/numba/numba or post to the Numba mailing list
https://groups.google.com/a/continuum.io/forum/#!forum/numba-users.

-->

## Reporting a bug

<!--

Before submitting a bug report please ensure that you can check off these boxes:

-->

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

<!--

Please include details of the bug here, including, if applicable, what you
expected to happen!

-->

```python
In [1]: import numba.cuda                                                       

In [2]: a = numba.cuda.device_array((10,))                                      

In [3]: a[...] = 1                                                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-4f8eed6187d7> in <module>
----> 1 a[...] = 1

/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py in _require_cuda_context(*args, **kws)
    223     def _require_cuda_context(*args, **kws):
    224         with _runtime.ensure_context():
--> 225             return fn(*args, **kws)
    226 
    227     return _require_cuda_context

/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py in __setitem__(self, key, value)
    528     @devices.require_context
    529     def __setitem__(self, key, value):
--> 530         return self._do_setitem(key, value)
    531 
    532     def setitem(self, key, value, stream=0):

/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py in _do_setitem(self, key, value, stream)
    541         # (1) prepare LHS
    542 
--> 543         arr = self._dummy.__getitem__(key)
    544         newdata = self.gpu_data.view(*arr.extent)
    545 

/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/numba/dummyarray.py in __getitem__(self, item)
    217             item.append(slice(None, None))
    218 
--> 219         dims = [dim.__getitem__(it) for dim, it in zip(self.dims, item)]
    220         newshape = [d.size for d in dims if not d.single]
    221 

/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/numba/dummyarray.py in <listcomp>(.0)
    217             item.append(slice(None, None))
    218 
--> 219         dims = [dim.__getitem__(it) for dim, it in zip(self.dims, item)]
    220         newshape = [d.size for d in dims if not d.single]
    221 

/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/numba/dummyarray.py in __getitem__(self, item)
     70             return ret
     71         else:
---> 72             sliced = self[item:item + 1]
     73             return Dim(
     74                 start=sliced.start,

TypeError: unsupported operand type(s) for +: 'ellipsis' and 'int'
```