---
tags: ["Needs-Tests"]
title: "BUG: Concatenating categorical datetime columns raises a ValueError since v1.2"
html_url: "https://github.com/pandas-dev/pandas/issues/39443"
user: "aiudirog"
repo: "pandas-dev/pandas"
---

