---
tags: ["Bug","ExtensionArray","Indexing","alignment","data-analysis","data-science","flexible","pandas","python"]
title: "BUG: _validate_setitem_value fails to raise for PandasArray"
html_url: "https://github.com/pandas-dev/pandas/issues/51044"
user: "jbrockmendel"
repo: "pandas-dev/pandas"
---

